import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryProvider from "@/app/providers/QueryProvider";
import {SidebarProvider, SidebarTrigger} from "@/shared/ui/sidebar";
import SidebarMenu from "@/widgets/sidebar";
import {SidebarLayouts} from "@/app/layouts/layouts";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <QueryProvider>
<SidebarLayouts>
    {children}
</SidebarLayouts>
   </QueryProvider>
      </body>
    </html>
  );
}
