export const surveys = [
    {
        id: 1,
        title: "Название анкеты",
        description: "Описание анкеты",
        status: "not_started",
        statusLabel: "Не начато",
        endDate: "Дата окончания",
        date: "Дата",
        duration: "Время прохождения",
        questions: "n вопросов",
        progress: 0,
        buttonText: "Начать заполнение",
    },
    {
        id: 2,
        title: "Название анкеты",
        description: "Описание анкеты",
        status: "in_progress",
        statusLabel: "В процессе",
        endDate: "Дата окончания",
        date: "Дата",
        duration: "Время прохождения",
        questions: "n вопросов",
        progress: 60,
        buttonText: "Продолжить заполнение",
    },
    {
        id: 3,
        title: "Название анкеты",
        description: "Описание анкеты",
        status: "completed",
        statusLabel: "Завершено",
        endDate: "Дата окончания",
        date: "Дата",
        duration: "Время прохождения",
        questions: "n вопросов",
        progress: 100,
        buttonText: "Продолжить заполнение",
    },
    {
        id: 4,
        title: "Название анкеты",
        description: "Описание анкеты",
        status: "not_started",
        statusLabel: "Не начато",
        endDate: "Дата окончания",
        date: "Дата",
        duration: "Время прохождения",
        questions: "n вопросов",
        progress: 0,
        buttonText: "Начать заполнение",
    },
    {
        id: 5,
        title: "Название анкеты",
        description: "Описание анкеты",
        status: "in_progress",
        statusLabel: "В процессе",
        endDate: "Дата окончания",
        date: "Дата",
        duration: "Время прохождения",
        questions: "n вопросов",
        progress: 45,
        buttonText: "Продолжить заполнение",
    },
    {
        id: 6,
        title: "Название анкеты",
        description: "Описание анкеты",
        status: "completed",
        statusLabel: "Завершено",
        endDate: "Дата окончания",
        date: "Дата",
        duration: "Время прохождения",
        questions: "n вопросов",
        progress: 100,
        buttonText: "Продолжить заполнение",
    },
]
